-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgAs+3BmUdQQEclv3B
bNh+u3t+YhqNAZscdBm7qPs1YH+gCgYIKoZIzj0DAQehRANCAARlg8wjNojSJFjD
hfV6Pj7uyKuafNqnL2Nk7kEb/hNRoTNt+Z11zdzCce+/rU0VeSqTej4B+d3Lq0gY
+iqNaRNE
-----END PRIVATE KEY-----